<?php
/**
 * TorTags component for Joomla 1.6, Joomla 1.7, Joomla 2.5, Joomla 3.x
 * @package TorTags
 * @author Tormix Team
 * @Copyright Copyright (C) Tormix, www.tormix.com
 * @license GNU/GPL http://www.gnu.org/copyleft/gpl.html
 */
defined('_JEXEC') or die('Restricted access');

jimport('joomla.application.component.controller');

class TorTagsControllerImpexp extends JController
{

    public function __construct($config = array())
    {
        parent::__construct($config);
    }

    public function exportnativetags()
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');

        $ct = $cl = 0;

        echo '<h1>Export TorTags tags to Joomla 3.x native tags log:</h1>';
        $db = JFactory::getDBO();

        $query = $db->getQuery(true);
        $query->select('`id`,`def_lang`');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $compnt = $db->loadObject();
        $cid = $compnt->id;
        $dl = $compnt->def_lang ? $compnt->def_lang : '*';
        if (!$cid)
            die('com_content not found...');

        $query = $db->getQuery(true);
        $query->select('tt.item_id');
        $query->select('g.title');
        $query->from('`#__tortags` as `tt`');
        $query->leftjoin('`#__tortags_tags` AS `g` ON `g`.`id`=`tt`.`tid`');
        $query->where('`tt`.`oid` =' . $cid);
        $db->setQuery($query);
        $content_tortags = $db->loadObjectList();
        if (sizeof($content_tortags)) {
            foreach ($content_tortags as $content_tortag) {

                //ADD TO #__TAGS
                JTable::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_tags/tables');
                $tagTable = JTable::getInstance('Tag', 'TagsTable');
                $tagText = $content_tortag->title;
                // Clear old data if exist
                $tagTable->reset();

                // Try to load the selected tag
                if ($tagTable->load(array('title' => $tagText))) {
                    $jtagid = (int)$tagTable->id;
                } else {
                    // Prepare tag data
                    $tagTable->id = 0;
                    $tagTable->title = $tagText;
                    $tagTable->published = 1;

                    // $tagTable->language = property_exists ($item, 'language') ? $item->language : '*';
                    $tagTable->language = '*';
                    $tagTable->access = 1;

                    // Make this item a child of the root tag
                    $tagTable->setLocation($tagTable->getRootId(), 'last-child');

                    // Try to store tag
                    if ($tagTable->check()) {
                        // Assign the alias as path (autogenerated tags have always level 1)
                        $tagTable->path = $tagTable->alias;

                        if ($tagTable->store()) {
                            $jtagid = (int)$tagTable->id;
                            $ct++;
                            echo '<div><span class="tt_succ_import"> New tag "' . $tagText . '" successfully created in Joomla Tags</span></div>';
                        }
                    }
                }
                if ($jtagid) {
                    $query = $db->getQuery(true);
                    $query->select('`content_item_id`');
                    $query->from('`#__contentitem_tag_map`');
                    $query->where('`content_item_id`=' . (int)$content_tortag->item_id);
                    $query->where('`type_alias`="com_content.article"');
                    $query->where('`tag_id`=' . (int)$jtagid);
                    $db->setQuery($query);
                    $alr_isset = $db->loadResult();
                    if (!$alr_isset) {
                        $query = $db->getQuery(true);
                        $query->select('`core_content_id`');
                        $query->from('`#__ucm_content`');
                        $query->where('`core_content_item_id`=' . (int)$content_tortag->item_id);
                        $query->where('`core_type_alias`="com_content.article"');
                        $db->setQuery($query);
                        $core_content_id = $db->loadResult();

                        $query = $db->getQuery(true);
                        $query->insert('#__contentitem_tag_map');
                        $query->set('`type_alias`="com_content.article"');
                        $query->set('`core_content_id`=' . (int)$core_content_id);
                        $query->set('`content_item_id`=' . (int)$content_tortag->item_id);
                        $query->set('`tag_id`=' . (int)$jtagid);
                        $query->set('`type_id`=1');
                        $db->setQuery($query);
                        $db->query();
                        $cl++;
                        echo '<div><span class="tt_succ_import">' . $tagText . ' new linked with article id=' . $content_tortag->item_id . '</span></div>';
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $ct . ' created, ' . $cl . ' connected)</span></div>';
    }

    public function importnativetags()
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');

        $ct = $cl = 0;

        echo '<h1>Import Joomla 3.x native tags log:</h1>';
        $db = JFactory::getDBO();

        $query = $db->getQuery(true);
        $query->select('`id`,`def_lang`');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $compnt = $db->loadObject();
        $cid = $compnt->id;
        $dl = $compnt->def_lang ? $compnt->def_lang : '*';
        if (!$cid)
            die('com_content not found...');

        $query = $db->getQuery(true);
        $query->select('`m`.`content_item_id`');
        $query->select('`t`.`title`');
        $query->from('`#__contentitem_tag_map` AS `m`');
        $query->leftjoin('`#__tags` AS `t` ON `t`.`id`=`m`.`tag_id`');
        $query->where('`m`.`type_alias`="com_content.article"');
        $db->setQuery($query);
        $native_tags = $db->loadObjectList();
        if (sizeof($native_tags)) {
            foreach ($native_tags as $native_tag) {
                $metakey = trim($native_tag->title);
                $query = $db->getQuery(true);
                $query->select('`id`');
                $query->from('`#__tortags_tags`');
                $query->where('`title`=' . $db->quote($metakey));
                $db->setQuery($query);
                $tid = $db->loadResult();
                if (!$metakey) continue;
                if (!$tid) {
                    $object = new stdclass();
                    $object->title = $metakey;
                    $object->language = $dl;
                    $object->published = 1;
                    $object->alias = TorTagsHelper::stringMainURLSafe($metakey);
                    $db->insertObject('#__tortags_tags', $object);
                    $tid = (int)$db->insertid();
                    $ct++;
                    echo '<div><span class="tt_succ_import"> New tag "' . $metakey . '" successfully added</span></div>';
                }

                $query = $db->getQuery(true);
                $query->select('`id`');
                $query->from('`#__tortags`');
                $query->where('`tid`=' . $tid);
                $query->where('`oid`=' . $cid);
                $query->where('`item_id`=' . $native_tag->content_item_id);
                $db->setQuery($query);
                $id = $db->loadResult();
                if ($id) {
                    //already exist
                } else {
                    $object = new stdclass();
                    $object->tid = $tid;
                    $object->oid = $cid;
                    $object->item_id = $native_tag->content_item_id;
                    if ($db->insertObject('#__tortags', $object)) {
                        $cl++;
                        echo '<div><span class="tt_succ_import">' . $metakey . ' new linked with article id=' . $native_tag->content_item_id . '</span></div>';
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $ct . ' created, ' . $cl . ' connected)</span></div>';
    }

    public function startmetaimport()
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');

        $ct = $cl = 0;

        echo '<h1>Import metakey log:</h1>';
        $db = JFactory::getDBO();

        $query = $db->getQuery(true);
        $query->select('`id`,`def_lang`');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $compnt = $db->loadObject();
        $cid = $compnt->id;
        $dl = $compnt->def_lang ? $compnt->def_lang : '*';
        if (!$cid)
            die('com_content not found...');

        $query = $db->getQuery(true);
        $query->select('*');
        $query->from('`#__content`');
        $query->where('`metakey`<>""');
        $query->where('(`state`=1 OR `state`=2)');
        $query->order('`title` ASC');
        $db->setQuery($query);
        $arts = $db->loadObjectList();

        if (sizeof($arts)) {
            foreach ($arts as $art) {
                $metakeys = explode(',', $art->metakey);
                if (sizeof($metakeys)) {
                    foreach ($metakeys as $metakey) {
                        $metakey = trim($metakey);
                        $query = $db->getQuery(true);
                        $query->select('`id`');
                        $query->from('`#__tortags_tags`');
                        $query->where('`title`=' . $db->quote($metakey));
                        $db->setQuery($query);
                        $tid = $db->loadResult();
                        if (!$tid) {
                            $object = new stdclass();
                            $object->title = $metakey;
                            $object->language = $dl;
                            $object->published = 1;
                            $object->alias = TorTagsHelper::stringMainURLSafe($metakey);
                            $db->insertObject('#__tortags_tags', $object);
                            $tid = (int)$db->insertid();
                            $ct++;
                            echo '<div><span class="tt_succ_import"> New tag "' . $metakey . '" successfully added</span></div>';
                        }

                        $query = $db->getQuery(true);
                        $query->select('`id`');
                        $query->from('`#__tortags`');
                        $query->where('`tid`=' . $tid);
                        $query->where('`oid`=' . $cid);
                        $query->where('`item_id`=' . $art->id);
                        $db->setQuery($query);
                        $id = $db->loadResult();
                        if ($id) {
                            //already exist
                        } else {
                            $object = new stdclass();
                            $object->tid = $tid;
                            $object->oid = $cid;
                            $object->item_id = $art->id;
                            if ($db->insertObject('#__tortags', $object)) {
                                $cl++;
                                echo '<div><span class="tt_succ_import">' . $metakey . ' new linked with article id=' . $art->id . '</span></div>';
                            }
                        }
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $ct . ' created, ' . $cl . ' connected)</span></div>';
    }

    public function importmeta()
    {
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('*');
        $query->from('`#__content`');
        $query->where('`metakey`<>""');
        $query->order('`title` ASC');
        $db->setQuery($query);
        $arts = $db->loadObjectList();
        if (sizeof($arts)) {
            echo '<form action="index.php?option=com_tortags&task=impexp.startmetaimport&tmpl=component" method="post" name="adminForm" id="item-form" >';
            echo '<input type="submit" class="submit button  btn btn-small" name="sumb" value="Start import" />';
            echo '<table class="adminlist table table-striped" style="width:100%;">';
            echo '<tr>';
            echo '<th width="1%">';
            echo JText::_('JGRID_HEADING_ID');
            echo '</th>';
            echo '<th>';
            echo JText::_('JGLOBAL_TITLE');
            echo '</th>';
            echo '<th>';
            echo JText::_('JFIELD_META_KEYWORDS_LABEL');
            echo '</th>';
            echo '<th>';
            echo JText::_('Attached tags');
            echo '</th>';
            echo '</tr>';

            foreach ($arts as $art) {
                echo '<tr>';
                echo '<td><div class="button2-left"><div class="blank">&nbsp;';
                echo $art->id;
                echo '&nbsp;</div></div></td>';
                echo '<td>';
                echo $art->title;
                echo '</td>';
                echo '<td>';
                echo $art->metakey;
                echo '</td>';
                echo '<td>';
                echo $this->getTagsByAid($art->id);
                echo '</td>';
                echo '</tr>';
            }
            echo '</table>';
            echo '<input type="submit" class="submit button  btn btn-small" name="sumb" value="Start import" />';
            echo '</form>';
        } else
            echo 'Articles with metakey not found.';
    }

    protected function getTagsByAid($aid = 0)
    {
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('*');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $oid = $db->loadResult();
        if (!$oid)
            return null;
        $query = $db->getQuery(true);
        $query->select('`tid`');
        $query->from('`#__tortags`');
        $query->where('`oid`=' . $oid);
        $query->where('item_id=' . $aid);
        $db->setQuery($query);
        $tagsids = $db->loadColumn();
        if (sizeof($tagsids)) {
            $query = $db->getQuery(true);
            $query->select('`title`');
            $query->from('`#__tortags_tags`');
            $query->where('`id` IN (' . implode(',', $tagsids) . ')');
            $db->setQuery($query);
            $tags = $db->loadColumn();
            if (sizeof($tags))
                echo implode(', ', $tags);
        }
        return null;
    }

    /*     * * EXPORT SECTION ** */

    protected function addTagToMeta($aid = 0, $tag = '', $comma = '')
    {
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->update('`#__content`');
        $query->set('`metakey`=CONCAT(`metakey`,"' . $comma . $tag . '")');
        $query->where('id=' . $aid);
        $db->setQuery($query);
        return $db->query();
    }

    public function startexportmeta()
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');

        $ca = 0;

        echo '<h1>Export tags log:</h1>';
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('id');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $cid = $db->loadResult();
        if (!$cid)
            die('com_content not found...');

        $query = $db->getQuery(true);
        $query->select('c.*');
        $query->from('`#__content` AS `c`');
        $query->where('`c`.`id` IN (SELECT `t`.`item_id` FROM `#__tortags` AS `t` WHERE `t`.`oid`=' . $cid . ')');
        $query->where('(`c`.`state`=1 OR `c`.`state`=2)');
        $query->order('`c`.`title` ASC');
        $db->setQuery($query);
        $arts = $db->loadObjectList();

        if (sizeof($arts)) {
            foreach ($arts as $art) {
                $query = $db->getQuery(true);
                $query->select('`g`.`title`');
                $query->from('`#__tortags_tags` AS `g`');
                $query->join('INNER', '`#__tortags` AS `t` ON `t`.`tid`=`g`.`id`');
                $query->where('`t`.`item_id`=' . $art->id);
                $query->where('`t`.`oid`=' . $cid);
                $query->order('`g`.`title` ASC');
                $db->setQuery($query);
                $tags = $db->loadColumn();
                if (sizeof($tags)) {
                    $metakeys = $rmetakeys = null;
                    if ($art->metakey)
                        $metakeys = explode(',', $art->metakey);
                    foreach ($tags as $k => $tag) {
                        if (sizeof($metakeys)) {
                            foreach ($metakeys as $metakey)
                                $rmetakeys[] = trim($metakey);

                            if (in_array($tag, $rmetakeys))
                                continue;
                            else {
                                $this->addTagToMeta($art->id, $tag, ',');
                                $ca++;
                                echo '<div><span class="tt_succ_import"> Tag "' . $tag . '" successfully added to article id=' . $art->id . '</span></div>';
                            }
                        } else {
                            $coma = ',';
                            if ($k == 0)
                                $coma = '';
                            $this->addTagToMeta($art->id, $tag, $coma);
                            $ca++;
                            echo '<div><span class="tt_succ_import"> Tag "' . $tag . '" successfully added to article id=' . $art->id . '</span></div>';
                        }
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $ca . ' tags added to meta)</span></div>';
    }

    public function exportmeta()
    {
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('id');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_content"');
        $db->setQuery($query);
        $cid = $db->loadResult();
        if (!$cid)
            die('com_content not found...');

        $query = $db->getQuery(true);
        $query->select('c.*');
        $query->from('`#__content` AS `c`');
        $query->where('`c`.`id` IN (SELECT `t`.`item_id` FROM `#__tortags` AS `t` WHERE `t`.`oid`=' . $cid . ')');
        $query->where('(`c`.`state`=1 OR `c`.`state`=2)');
        $query->order('`c`.`title` ASC');
        $db->setQuery($query);
        $arts = $db->loadObjectList();
        if (sizeof($arts)) {
            echo '<form action="index.php?option=com_tortags&task=impexp.startexportmeta&tmpl=component" method="post" name="adminForm" id="adminForm" >';
            echo '<input type="submit" class="submit button  btn btn-small" name="sumb" value="Start export to meta" />';
            echo '<table class="adminlist table table-striped" style="width:100%;">';
            echo '<tr>';
            echo '<th width="1%">';
            echo JText::_('JGRID_HEADING_ID');
            echo '</th>';
            echo '<th>';
            echo JText::_('JGLOBAL_TITLE');
            echo '</th>';
            echo '<th>';
            echo JText::_('Attached tags');
            echo '</th>';
            echo '<th>';
            echo JText::_('JFIELD_META_KEYWORDS_LABEL');
            echo '</th>';
            echo '</tr>';

            foreach ($arts as $art) {
                echo '<tr>';
                echo '<td><div class="button2-left"><div class="blank  btn btn-small">&nbsp;';
                echo $art->id;
                echo '&nbsp;</div></div></td>';
                echo '<td>';
                echo $art->title;
                echo '</td>';
                echo '<td>';
                echo $this->getTagsByAid($art->id);
                echo '</td>';
                echo '<td>';
                echo $art->metakey;
                echo '</td>';
                echo '</tr>';
            }
            echo '</table>';
            echo '<input type="submit" class="submit button  btn btn-small" name="sumb" value="Start export to meta" />';
            echo '</form>';
        } else
            echo 'Tags in content not found.';
    }

    /*     * *SINH SECTION** */

    public function sinchronize()
    {
        $comp = JRequest::getVar('comp');

        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');
        switch ($comp) {
            case 'easyblog':
                $this->startEasyBlogSinchr();
                break;

            case 'easydiscuss':
                $this->startEasyDiscussSinchr();
                break;

            case 'virtuemart':
                $this->startVirtueMartSinchr();
                break;
        }
    }

    private function startVirtueMartSinchr()
    {

        $ct = $cl = 0;

        echo '<h1>Sinchronization of tags - log:</h1>';
        $db = JFactory::getDBO();

        $query = $db->getQuery(true);
        $query->select('id');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_virtuemart"');
        $db->setQuery($query);
        $cid = $db->loadResult();
        if (!$cid)
            die('com_virtuemart not found in tortags components...');

        $query = $db->getQuery(true);
        $query->select('`config`');
        $query->from('`#__virtuemart_configs`');
        $db->setQuery($query);
        $vm_conf = $db->loadResult();

        $vm_lang = "en_gb";

        if ($vm_conf)
            $vm_config = explode('|', $vm_conf);
        if (sizeof($vm_config))
            foreach ($vm_config as $item) {
                $item = explode('=', $item);
                if (!empty($item[1])) {
                    if ($item[0] == 'vmlang') {
                        $vm_lang = @unserialize($item[1]);
                    }
                }
            }


        $query = $db->getQuery(true);
        $query->select('`virtuemart_product_id` AS `id`,`metakey`');
        $query->from('`#__virtuemart_products_' . $vm_lang . '` AS `vmp`');
        $query->where('`metakey`<>""');
        $db->setQuery($query);
        $vm_products = $db->loadObjectList();

        if (sizeof($vm_products)) {
            foreach ($vm_products as $vm_product) {
                $metakeys = explode(',', $vm_product->metakey);
                if (sizeof($metakeys)) {
                    foreach ($metakeys as $metakey) {
                        $metakey = trim($metakey);
                        $query = $db->getQuery(true);
                        $query->select('`id`');
                        $query->from('`#__tortags_tags`');
                        $query->where('`title`=' . $db->quote($metakey));
                        $db->setQuery($query);
                        $tid = $db->loadResult();
                        if (!$tid) {
                            $object = new stdclass();
                            $object->title = $metakey;
                            $object->language = '*';
                            $object->published = 1;
                            $object->alias = TorTagsHelper::stringMainURLSafe($metakey);
                            $db->insertObject('#__tortags_tags', $object);
                            $tid = (int)$db->insertid();
                            $ct++;
                            echo '<div><span class="tt_succ_import"> New tag "' . $metakey . '" successfully added</span></div>';
                        }

                        $query = $db->getQuery(true);
                        $query->select('`id`');
                        $query->from('`#__tortags`');
                        $query->where('`tid`=' . $tid);
                        $query->where('`oid`=' . $cid);
                        $query->where('`item_id`=' . $vm_product->id);
                        $db->setQuery($query);
                        $id = $db->loadResult();
                        if ($id) {
                            //already exist
                        } else {
                            $object = new stdclass();
                            $object->tid = $tid;
                            $object->oid = $cid;
                            $object->item_id = $vm_product->id;
                            if ($db->insertObject('#__tortags', $object)) {
                                $cl++;
                                echo '<div><span class="tt_succ_import">' . $metakey . ' new linked with vm_id id=' . $vm_product->id . '</span></div>';
                            }
                        }
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $ct . ' new tags and ' . $cl . ' new connections of tags added to TorTags)</span></div>';
    }

    private function startEasyBlogSinchr()
    {
        $ca = $cn = 0;

        echo '<h1>Sinchronization of tags - log:</h1>';
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('id');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_easyblog"');
        $db->setQuery($query);
        $cid = $db->loadResult();

        if (!$cid)
            die('com_easyblog not found...');

        $query = $db->getQuery(true);
        $query->select('p.*,et.title');
        $query->from('`#__easyblog_post_tag` AS `p`');
        $query->leftjoin('`#__easyblog_tag` AS `et` on `et`.`id`=`p`.`tag_id`');
        $db->setQuery($query);
        $discuss = $db->loadObjectList();

        if (sizeof($discuss)) {
            echo '<div class="tt_import">Information: Found ' . count($discuss) . ' EasyBlog tags connections:</div>';
            foreach ($discuss as $disc) {
                $tagtitle = $disc->title;
                $query = $db->getQuery(true);
                $query->select('`id`');
                $query->from('`#__tortags_tags`');
                $query->where('`title`=' . $db->quote($tagtitle));
                $db->setQuery($query);
                $tid = $db->loadResult();
                if (!$tid) {
                    $object = new stdclass();
                    $object->title = $tagtitle;
                    $object->language = '*';
                    $object->published = 1;
                    $object->alias = TorTagsHelper::stringMainURLSafe($tagtitle);
                    $db->insertObject('#__tortags_tags', $object);
                    $tid = (int)$db->insertid();
                    $cn++;
                    echo '<div class="tt_succ_import">New tag  "' . $tagtitle . '" successfully created</div>';
                }
                if ($tid) {
                    $query = $db->getQuery(true);
                    $query->select('`t`.`id`');
                    $query->from('`#__tortags` AS `t`');
                    $query->where('`t`.`item_id`=' . $disc->post_id);
                    $query->where('`t`.`tid`=' . (int)$tid);
                    $query->where('`t`.`oid`=' . $cid);
                    $db->setQuery($query);
                    $issettag = $db->loadResult();
                    if (!$issettag) {
                        $query->insert('#__tortags');
                        $query->set('`tid`=' . $tid);
                        $query->set('`oid`=' . $cid);
                        $query->set('`item_id`=' . $disc->post_id);
                        $db->setQuery($query);
                        $db->query();
                        echo '<div class="tt_succ_import">New tag connection for "' . $tagtitle . '" for EasyBlog id ' . $disc->post_id . ' successfully added</div>';
                        $ca++;
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $cn . ' new tags and ' . $ca . ' new connections of tags added to TorTags)</span></div>';
    }

    private function startEasyDiscussSinchr()
    {

        $ca = $cn = 0;

        echo '<h1>Sinchronization of tags - log:</h1>';
        $db = JFactory::getDBO();
        $query = $db->getQuery(true);
        $query->select('id');
        $query->from('`#__tortags_components`');
        $query->where('`component`="com_easydiscuss"');
        $db->setQuery($query);
        $cid = $db->loadResult();

        if (!$cid)
            die('com_easydiscuss not found...');

        $query = $db->getQuery(true);
        $query->select('p.*,dt.title');
        $query->from('`#__discuss_posts_tags` AS `p`');
        $query->leftjoin('`#__discuss_tags` AS `dt` on `dt`.`id`=`p`.`tag_id`');
        $db->setQuery($query);
        $discuss = $db->loadObjectList();

        if (sizeof($discuss)) {
            echo '<div class="tt_import">Information: Found ' . count($discuss) . ' discuss tags connections:</div>';
            foreach ($discuss as $disc) {
                $tagtitle = $disc->title;
                $query = $db->getQuery(true);
                $query->select('`id`');
                $query->from('`#__tortags_tags`');
                $query->where('`title`=' . $db->quote($tagtitle));
                $db->setQuery($query);
                $tid = $db->loadResult();
                if (!$tid) {
                    $object = new stdclass();
                    $object->title = $tagtitle;
                    $object->language = '*';
                    $object->published = 1;
                    $object->alias = TorTagsHelper::stringMainURLSafe($tagtitle);
                    $db->insertObject('#__tortags_tags', $object);
                    $tid = (int)$db->insertid();
                    $cn++;
                    echo '<div class="tt_succ_import">New tag  "' . $tagtitle . '" successfully created</div>';
                }
                if ($tid) {
                    $query = $db->getQuery(true);
                    $query->select('`t`.`id`');
                    $query->from('`#__tortags` AS `t`');
                    $query->where('`t`.`item_id`=' . $disc->post_id);
                    $query->where('`t`.`tid`=' . (int)$tid);
                    $query->where('`t`.`oid`=' . $cid);
                    $db->setQuery($query);
                    $issettag = $db->loadResult();
                    if (!$issettag) {
                        $query->insert('#__tortags');
                        $query->set('`tid`=' . $tid);
                        $query->set('`oid`=' . $cid);
                        $query->set('`item_id`=' . $disc->post_id);
                        $db->setQuery($query);
                        $db->query();
                        echo '<div class="tt_succ_import">New tag connection for "' . $tagtitle . '" for discuss id ' . $disc->post_id . ' successfully added</div>';
                        $ca++;
                    }
                }
            }
        }
        echo '<div><span class="tt_succ_import">FINISHED (' . $cn . ' new tags and ' . $ca . ' new connections of tags added to TorTags)</span></div>';
    }

    /*     * * MIGRATION ** */

    public function jtmigration()
    {

        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');
        ?>

        <?php
        $db = JFactory::getDBO();

        $query = "SHOW TABLES LIKE '%tag_term'";
        $db->setQuery($query);
        $tag_term = $db->loadResult();
        $query = "SHOW TABLES LIKE '%tag_term_content%'";
        $db->setQuery($query);
        $tag_term_content = $db->loadResult();

        if ($tag_term && $tag_term_content) {
            ?>
            <h3><?php echo JText::_('COM_TORTAGS_MIGRATION_JOOMLATAG_STEP2'); ?></h3>
            <?php
            $db->setQuery("SELECT * FROM `" . $tag_term . "`");
            $list_objs = $db->loadObjectList();
            if (sizeof($list_objs)) {
                foreach ($list_objs as $tags) {
                    $db->setQuery("SELECT `id` FROM `#__tortags_tags` WHERE `title`='" . $tags->name . "'");
                    $db->query();
                    $tag_id = $db->loadResult();

                    if (!$tag_id) {
                        $object = new stdclass();
                        $object->title = $tags->name;
                        $object->language = '*';
                        $object->published = 1;
                        $object->alias = TorTagsHelper::stringMainURLSafe($tags->name);
                        $db->insertObject('#__tortags_tags', $object);
                        $tag_id = $db->insertid();
                        echo '<div class="tt_succ_import">New tag "' . $tags->name . '" successfully added</div>';
                    } else
                        echo '<div class="tt_succ_import">Tag "' . $tags->name . '" is already isset</div>';
                }
            }
            ?>
            <h3><?php echo JText::_('COM_TORTAGS_MIGRATION_JOOMLATAG_STEP3'); ?></h3>
            <?php
            $db->setQuery("SELECT `id` FROM `#__tortags_components` WHERE `component`='com_content'");
            $db->query();
            $comp_id = $db->loadResult();

            $db->setQuery("SELECT * FROM `" . $tag_term_content . "`");
            $list_objs = $db->loadObjectList();

            if (sizeof($list_objs)) {
                foreach ($list_objs as $map) {
                    $db->setQuery("SELECT `name` FROM `" . $tag_term . "` WHERE `id`=" . $map->tid);
                    $db->query();
                    $jtagtitle = $db->loadResult();

                    $db->setQuery("SELECT `id` FROM `#__tortags_tags` WHERE `title`='" . $jtagtitle . "'");
                    $db->query();
                    $tag_id = $db->loadResult();

                    $db->setQuery("SELECT `id` FROM `#__tortags` WHERE `tid`='" . $tag_id . "' AND `oid`='" . $comp_id . "' AND `item_id`='" . $map->cid . "' ");
                    $map_id = $db->loadResult();

                    if (!$map_id) {
                        $db->setQuery("INSERT INTO `#__tortags` (`id` ,`tid` ,`oid` ,`item_id`)
														VALUES ( NULL , '" . $tag_id . "', '" . $comp_id . "', '" . $map->cid . "');");
                        $db->query();
                        $opt_id = $db->insertid();
                        echo '<p style="padding-left: 21px;"><div class="tt_succ_import">Link "' . $tag_id . '+' . $comp_id . '+' . $map->cid . '" successfully added</div></p>';
                    } else
                        echo '<p style="padding-left: 21px;"><div class="tt_succ_import">Link "' . $tag_id . '+' . $comp_id . '+' . $map->cid . '" is already isset</div></p>';
                }
            }
            ?>
            <div class="tt_succ_import"><b>Completed</b></div>
        <?php
        }
    }

    public function jxlabelsmigration()
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_tortags/assets/css/tortags.css');
        ?>

        <?php
        $db = JFactory::getDBO();

        $query = "SHOW TABLES LIKE '%jxlabels_labels%'";
        $db->setQuery($query);
        $jxlabels_labels = $db->loadResult();
        $query = "SHOW TABLES LIKE '%jxlabels_maps%'";
        $db->setQuery($query);
        $jxlabels_maps = $db->loadResult();
        $query = "SHOW TABLES LIKE '%jxlabels_types%'";
        $db->setQuery($query);
        $jxlabels_types = $db->loadResult();

        if ($jxlabels_labels && $jxlabels_maps && $jxlabels_types) {
            ?>
            <h3><?php echo JText::_('COM_TORTAGS_MIGRATION_STEP2'); ?></h3>
            <?php
            $db->setQuery("SELECT * FROM `" . $jxlabels_labels . "`");
            $list_objs = $db->loadObjectList();
            if (sizeof($list_objs)) {
                foreach ($list_objs as $tags) {
                    $db->setQuery("SELECT `id` FROM `#__tortags_tags` WHERE `title`='" . $tags->title . "'");
                    $db->query();
                    $tag_id = $db->loadResult();

                    if (!$tag_id) {
                        $object = new stdclass();
                        $object->title = $tags->title;
                        $object->language = '*';
                        $object->published = 1;
                        $object->alias = TorTagsHelper::stringMainURLSafe($tags->title);
                        $db->insertObject('#__tortags_tags', $object);
                        $tag_id = $db->insertid();
                        echo '<div class="tt_succ_import">New tag "' . $tags->title . '" successfully added</div>';
                    } else
                        echo '<div class="tt_succ_import">Tag "' . $tags->title . '" is already isset</div>';
                }
            }
            ?>
            <h3><?php echo JText::_('COM_TORTAGS_MIGRATION_STEP3'); ?></h3>
            <?php
            $db->setQuery("SELECT * FROM `" . $jxlabels_types . "`");
            $list_objs = $db->loadObjectList();

            if (sizeof($list_objs)) {
                foreach ($list_objs as $type) {
                    $db->setQuery("SELECT `id` FROM `#__tortags_components` WHERE `component`='" . $type->component . "'");
                    $db->query();
                    $comp_id = $db->loadResult();

                    if (!$comp_id) {
                        $a = $b = array();
                        $a[] = $type->component;
                        $b[] = '[COMPONENT]';
                        $a[] = '&id=';
                        $b[] = '&id=[ID]';

                        $urltempl = str_replace($a, $b, $type->front_link);
                        $db->setQuery("INSERT INTO `#__tortags_components` (`id`, `component`, `table`, `id_field`, `title_field`, `description_field`, `created_field`, `url_template`, `exc_views`,`be_key`,`fe_key`,`state_field`,`state_status`) 
												VALUES ( NULL , '" . $type->component . "', '" . $type->table_name . "','" . $type->table_key . "','" . $type->table_title . "','" . $type->table_text . "','" . $type->table_date . "','" . $urltempl . "', '" . $type->admin_request_key . "','" . $type->site_request_key . "','" . $type->table_state . "','" . $type->table_pub_state . "' );");
                        $db->query();
                        $comp_id = $db->insertid();
                        echo '<div class="tt_succ_import">Component settings "' . $type->component . '" successfully added</div>';
                    } else
                        echo '<div class="tt_succ_import">Component settings for "' . $type->component . '" is already isset</div>';

                    $db->setQuery("SELECT * FROM `" . $jxlabels_maps . "` WHERE `type_id`=" . $type->type_id);
                    $list_options = $db->loadObjectList();
                    if (sizeof($list_options)) {
                        foreach ($list_options as $map) {
                            $db->setQuery("SELECT `title` FROM `" . $jxlabels_labels . "` WHERE `label_id`=" . $map->label_id);
                            $db->query();
                            $jxtagtitle = $db->loadResult();

                            $db->setQuery("SELECT `id` FROM `#__tortags_tags` WHERE `title`='" . $jxtagtitle . "'");
                            $db->query();
                            $tag_id = $db->loadResult();

                            $db->setQuery("SELECT `id` FROM `#__tortags` WHERE `tid`='" . $tag_id . "' AND `oid`='" . $comp_id . "'  AND `item_id`='" . $map->item_id . "'");
                            $map_id = $db->loadResult();

                            if (!$map_id) {

                                $db->setQuery("INSERT INTO `#__tortags` (`id` ,`tid` ,`oid` ,`item_id`)
														VALUES ( NULL , '" . $tag_id . "', '" . $comp_id . "', '" . $map->item_id . "');");
                                $db->query();
                                $opt_id = $db->insertid();
                                echo '<p style="padding-left: 21px;"><div class="tt_succ_import">Link "' . $tag_id . '+' . $comp_id . '+' . $map->item_id . '" successfully added</div></p>';
                            } else
                                echo '<p style="padding-left: 21px;"><div class="tt_succ_import">Link "' . $tag_id . '+' . $comp_id . '+' . $map->item_id . '" is already isset</div></p>';
                        }
                    }
                }
            }
            /* ITEMS aka (old)rows */
            ?>
            <div class="tt_succ_import"><b>Completed</b></div>
            <br/>
            <small><?php echo JText::_('COM_TORTAGS_MIGRATION_STEP3_NOTE'); ?></small>
        <?php
        }
    }

}
